spring.application.name=RankingGame
spring.datasource.url=jdbc:postgresql://localhost:5432/ranking_game
spring.datasource.username=rankinggame
spring.datasource.password=rankinggame
spring.jpa.hibernate.ddl-auto=validate
