GET http://localhost:8080/api/rooms/18SPUR/ranking-game/rounds/243598ad-0011-4a8c-bebe-790b75e2a21d/answer/position/all?
    playerId=c0529da4-9900-4865-b3c6-a0e86b074212
Accept: application/json

###
